name: beta

on:
  push:
    branches:
      - dev

jobs:
  build_beta:
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: echo "CURRENT_DATE=$(date --rfc-3339=seconds)" >> $GITHUB_OUTPUT

      - name: Checkout
        uses: actions/checkout@v4

      - name: Clone external repository
        run: git clone https://gitlab.com/apt-mirror2/apt-mirror2.git ./apt-mirror2 && cd ./apt-mirror2 && ls -l

      - name: login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./beta
          file: ./beta/Dockerfile
          tags: |
            shirokumo/apt-mirror2:beta
          labels: |
            org.opencontainers.image.created=${{ steps.date.outputs.CURRENT_DATE }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.title=apt-mirror2
            org.opencontainers.image.description=一个apt-mirror2的docker实现，添加了Nginx服务。A docker implementation of apt-mirror2 with Nginx service added.
            org.opencontainers.image.licenses=GPL-3.0-or-later
            org.opencontainers.image.authors=White-Clouds
            org.opencontainers.image.source=https://github.com/White-Clouds/apt-mirror2-docker
            org.opencontainers.image.url=https://github.com/White-Clouds/apt-mirror2-docker
            org.opencontainers.image.version=beta
          push: true
